# Generated by Django 5.2.11 on 2026-06-10 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_alter_campaignlead_status"),
        ("campaigns", "0007_email_template"),
    ]

    operations = []
