# Generated by Django 5.2.11 on 2026-06-10 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_blockeddomain"),
        ("leads", "0002_lead_custom_variables"),
    ]

    operations = []
